# Generated by Django 3.2.3 on 2021-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0002_auto_20210503_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autograderuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
