# Generated by Django 3.2.3 on 2022-06-07 05:43

import autograder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autograder', '0003_alter_autograderuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source_file',
            field=models.FileField(upload_to=autograder.models.submission_path),
        ),
    ]
